name: Release

on:
    push:
        branches: [vfront-release]
    workflow_dispatch:
jobs:
    Setup:
        name: Setup
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Cache node modules
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Use Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Npm install and build
              run: |
                  npm ci
                  npm run build

            - name: Delete Existing Release
              uses: dev-drprasad/delete-tag-and-release@v1.0
              with:
                  delete_release: true
                  tag_name: latest
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: vfront.zip
                  tag_name: latest